name: tencent_flutter_apns
description: APNS push notification plugin. Uses firebase_messaging on Android, but replaces it on iOS with custom implementation.
version: 2.0.0
homepage: https://github.com/mwaylabs/flutter-apns
publish_to: "none" # Remove this line if you wish to publish to pub.

plugin:
  platforms:
    android:
      pluginClass: FirebasePushConnector
    ios:
      pluginClass: ApnsPushConnector

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.1
  firebase_messaging: 14.7.10
  flutter_apns_only: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
